base/contracts

script/universal/Simulator.sol

Tenderly's nginx has a URI limit of somewhere just over 8000 characters. This PR removes the `rawFunctionInput` query parameter if the URI is too long, and instead prints it separately for the user to copy/paste.

Avoid printing long Tenderly URLs

---

Makefile

Errors out at the moment because it says lib exists and is not empty if you re-install deps.

Fix `make deps`

---

script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol

This change adds a new environment variable called `SAFE_NONCE` which allow callers to override the Safe contract nonce.
This is useful when crafting future transactions ahead of time and collecting signatures.
It also provides a new `function verify(bytes memory _signatures)` to make sure the collected signatures are valid to execute the transaction.
It is intended to work as:
1. Maintainer craft a transaction ahead of time
2. Multiple signer parties are contacted and sign the transaction offline
3. Maintainer collect and verify the presigned transactions
4. Transaction with signatures are stored safely for later execution

feat: override safe nonce and verify signatures

---

script/universal/MultisigBase.sol

I noticed when the env `SAFE_NONCE` was missing, the script failed because it couldn't convert an empty string("") into uint256.
This change checks the value of the env var before attempting to parse it.

fix: check optional environment variable as string before parsing into uint256

---

script/universal/MultisigBase.sol

When SAFE_NONCE is not set, the script fails with
```
├─ [0] VM::envString("SAFE_NONCE") [staticcall]
│   └─ ← environment variable "SAFE_NONCE" not found
└─ ← environment variable "SAFE_NONCE" not found
```
This change replaces `envString` to `envOr` defaulting to an empty string.

fix: safe_nonce env shouldnt be required

---

script/deploy/l1/tests/TestDeposits.s.sol
script/deploy/l2/tests/DeployTestTokenContracts.s.sol
script/deploy/l2/tests/TestWithdraw.s.sol
script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol
script/universal/Simulator.sol
src/revenue-share/BalanceTracker.sol
src/revenue-share/FeeDisburser.sol
test/Challenger1of2.t.sol
test/fee-vault-fixes/e2e/FeeVault.t.sol
test/revenue-share/BalanceTracker.t.sol
test/revenue-share/FeeDisburser.t.sol
test/revenue-share/mocks/FeeVaultRevert.sol

Allow for more recent solc version for Multisig builder scripts, since there's no reason really to restrict it to only 0.8.15.
Also fix some dependency path issues that came up since Optimism's repo structure changed

Flexible version for universal scripts

---

script/universal/MultisigBuilder.sol
script/universal/Simulator.sol

With some upcoming config changes, we need more granular control over the Multisig signature simulations. This PR implements two changes: 
1. The `_simulateForSigner` method is now `virtual` so that an inheriting contract can overwrite its logic if need be. 
2. New method `overrideSafeThresholdOwnerAndNonce` has been added to give additonal flexibility in overwriting the safe's state for simulation calls.

Add new hooks to Multisig tooling for better simulation control 

---

script/universal/Simulator.sol

Cleanup of simulator overrides to add them one-by-one. Also removes one unnecessary override (the `keccak256(0 || 2)` if `owner == address(0)`).

Simulator override refactor

---

script/universal/MultisigBuilder.sol

The new hook `_addOverrides` in `MultisigBuilder` allows for arbitrary override capacity in an inheriting script. This is cleaner than overwriting the entirety of `_simulateForSigner` when most of the method is left unaffected. 
I've left `_simulateForSigner` as virtual in case the `_addOverrides` hook doesn't offer enough flexibility.

Add overrides hook 

---

script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol

Cleanup multiple instances of the same `try/catch` statement to look for .env nonce override. The new method is `virtual` so that inheriting scripts will have more flexibility over explicitly setting the Nonce value for a given safe transaction.

Add virtual method for explicit nonce overriding 

---

script/universal/MultisigBuilder.sol

It allows an inheriting contract to define a method which overrides `_addGenericOverride`. This allows the caller to add arbitrary contact state diffs. When this virtual method isn't overriden in an inheriting contract, an empty override is appended instead (no-op in Tenderly).

Add a generic state override for tenderly sims 

---

script/universal/MultisigBase.sol

See description in https://github.com/base-org/contract-deployments/pull/149 for motivation here.

Add clearer messaging around the risks of overwriting _getNonce

---

script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol
script/universal/Simulator.sol

To facilitate the following features:
1. State diff assertions using state diffs from foundry.
2. Exposing transaction simulation payloads for simulating with external tools such as Tenderly.
3. Failing when a simulation or execution reverts or does not result in any state changes.
The below changes were made:
1. The postCheck hook takes state diff and simulation payload inputs.
2. The postCheck hook is mutable to enable ffi calls to further validate the transaction results.
3. Anytime a transaction is executed, whether simulated or broadcast, the state diff is recorded and returned to the caller.
4. The postCheck hook is always run after a transaction, whether simulated or broadcast.
5. Booleans returned from methods have been removed, as the methods will now revert if a transaction …

feat: simulates transactions in forge and exposes state diff and sim info

---

src/Vetoer1of2.sol

Creates a Vetoer1of2 for the initial Security Council migration. This contract is meant to hold the `VETOER` role as defined in the [DelayedVetoable](https://github.com/ethereum-optimism/optimism/blob/d72fb46daf3a6831cb01a78931f8c6e0d52ae243/packages/contracts-bedrock/src/L1/DelayedVetoable.sol) contract.

Add Vetoer1of2 from Challenger1of2

---

src/Vetoer1of2.sol

Minimal residual typo from moving `Challenger1of2.sol` to `Vetoer1of2.sol`

Amend typo

---

script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol

We recently merged https://github.com/base-org/contracts/pull/72. Prior to this PR, foundry did not simulate the transaction, and just logged the data needed to generate the tenderly sim. As a result, when forge called `safe.nonce()` at the very end of the solidity script, it matched what was on the actual chain.
In that PR, we modified the scripts so forge always applies the required state overrides and simulates the transaction. This was done so we can use the state diff recording cheats in foundry and make assertions on the diff.
However, the actual logging of the `Data to sign:` that's in the terminal calls `safe.nonce()` _after_ the foundry simulation, so it's one too high.
This PR snapshots the safe nonce prior to simulation and restores it after, so the data to sign is corrected …

fix: snapshot and restore Safe nonce

---

script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol

Previously, when fetching the original nonce to restore after a simulation, it would restore to the nonce fetched from the RPC. This PR fixes that so the original nonce is obtained using the `_getNonce` method, which overrides the fetched nonce with the env var nonce, if the env var is set (h/t @emilianobonassi)

fix: respect env var nonce when fetching original nonce

---

src/Vetoer1of2.sol

This PR simplifies the deployment of the `Vetoer1of2` along with its associated `DelayedVetoable` contract by removing the circular dependency between both of them.
The `DELAYED_VETOABLE` immutable set at deployment in the `Vetoer1of2` is replaced by the additional `delayedVetoable`parameter that must be provided when calling the `execute` method.
Additionally, variables have been renamed to match with our [style guide](https://github.com/coinbase/solidity-style-guide).

Remove the `delayedVetoable` param from the `Vetoer1of2` constructor 

---

script/universal/MultisigBase.sol

Checking the terminals domain + message hash matches what's displayed on a signers hardware wallet and simulation is an imperative step in the process. 
The run book does instruct signers to do this but reinforcement of this message is very important.
This PR changes the output slightly. Below is a screenshot of this change in action:

Addition of important log message for signers

---

script/universal/NestedMultisigBuilder.sol

**Problem**: In the nested Safe case, we want to sign multiple transactions up-front, then execute them one after another. This requires overriding the safe nonce in advance. However, this is not currently supported for the nested Safe case.
**Solution**: In `NestedMultisigBuilder`, override the `_getNonce` method to change how we look for nonce overrides, and apply these overrides in `_simulateForSigner`. We cannot use the existing `SAFE_NONCE` env var since that is ambiguous in the nested context. Therefore the nested case now looks for env vars of the name `SAFE_NONCE_{UPPERCASE_SAFE_ADDRESS}` (example: `SAFE_NONCE_0X6DF4742A3C28790E63FE933F7D108FE9FCE51EA4`). While an uppercased address looks a little funny and isn't conventional, this preserves the UPPERCASE env var naming convention …

feat: support nonce overrides for nested safes

---

src/smart-escrow/SmartEscrow.sol

This PR incorporates feedback from the second smart contract escrow audit conducted by spearbit:
1.  will do
2.  I think that the clearer error messaging on construction is more helpful than the minimal gas removing the check saves. Won't do
3. Same reasoning as 2). Won't do
4. See PR comments below for context; ultimately; No change needed. 
--- FROM SPEARBIT --- 
1. Redundant contractTerminated check, will be checked in release()
https://github.com/base-org/contracts/blob/b49add823005826521b5b8d8cf8a7a292420f0bd/src/smart-escrow/SmartEscrow.sol#L186
3. https://github.com/base-org/contracts/blob/b49add823005826521b5b8d8cf8a7a292420f0bd/src/smart-escrow/SmartEscrow.sol#L155-L157
if (_start >= _end) revert StartTimeAfterEndTime(_start, _end);
Technically redundant as it will be covered by …

SmartEscrow Audit Feedback 

---

script/universal/MultisigBuilder.sol

Adds a new virtual function `_addMultipleGenericOverrides` which can be used to set overrides for multiple contracts.
The new function can be used alongside or instead of `_addGenericOverrides` thus maintaining backwards compatibility with pre-existing scripts. 
This PR also slightly improves the UX of reviewing a simulation, as empty overrides will no longer be included in the Tenderly URL. Previously these empty overrides also appeared in  the list of State Overrides on Tenderly.

Allow adding multiple contract overrides

---

src/revenue-share/BalanceTracker.sol

We want to redeploy this with different target balances. This will allow us to reinitialize the targets + balances stored in the proxy.

Allow reinitialization of the BalanceTracker

---

src/smart-escrow/SmartEscrow.sol
test/smart-escrow/Constructor.t.sol

we had a check that the start time of the contract was not in the past, but this is now the case, so removing this check

Remove start time check on SmartEscrow

---

script/universal/IGnosisSafe.sol
script/universal/MultisigBase.sol

The optimism contracts use a strict pragma for compilation (`=0.8.15`) that makes it challenging to use the Multisig builder infra in other contexts. Instead of requiring that all users of our MS builder infra comply with this pragma or implement complicated foundry.toml compiler overrides, I've moved the IGnosisSafe interface into the scope of this repo. 
This means that integrators can clone this repo without needing the optimism contracts (and thereby leverage a more flexible pragma).

Move IGnosisSafe into this repo to remove extraneous dependency on op-contracts

---

script/deploy/l1/SetGasLimitBuilder.sol

Adds new `SetGasLimitBuilder` abstract script which simplifies the repeated task of calling the `setGasLimit` L1 system config method via a gnosis multisig.
To use this, a child class must implement the following 3 virtual function:
```solidity
function _fromGasLimit() internal virtual view returns (uint64);
function _toGasLimit() internal virtual view returns (uint64);
function _nonceOffset() internal virtual view returns (uint64);
```
It's expected that the nonce offset will typically be set to 0 for upgrades or 1 for pre-signed rollbacks, while the from and to gas limits may be reversed. It's also possible to use this to pre-sign a number of sequential upgrades and/or rollbacks.
See https://github.com/base-org/contract-deployments/compare/main...example-gas-limit-upgrade for an example …

feat: Add L1 SetGasLimitBuilder abstract script

---

script/deploy/l1/RollbackGasLimit.sol
script/deploy/l1/UpgradeGasLimit.sol

Builds upon #91, adding standard `UpgradeGasLimit` and `RollbackGasLimit` scripts. This allows us to perform repeatable gas limit upgrades with pre-signed rollbacks without adding any new solidity to base-org/contract-deployments

feat: Add Upgrade and Rollback GasLimit scripts

---

script/deploy/l1/RollbackGasLimit.sol
script/deploy/l1/SetGasLimitBuilder.sol
script/deploy/l1/UpgradeGasLimit.sol

Allows the `UPGRADE_NONCE_OFFSET` and `ROLLBACK_NONCE_OFFSET` env vars to override the nonce offsets for gas limit upgrades and rollbacks respectively, allowing users to more easily pre-sign multiple upgrades and/or rollbacks.

feat: Allow env nonce overrides for gas limit changes

---

script/universal/MultisigBase.sol

Safe doesn't allow duplicate signers (nor does it make sense): https://github.com/safe-global/safe-smart-account/blob/1ed486bb148fe40c26be58d1b517cec163980027/contracts/Safe.sol#L331
If you pass duplicate sigs into the `signatures`, currently the tx will revert. This bit the OP folks recently when they passed an address from a signer that was in `approvedHashes` (see https://github.com/ethereum-optimism/superchain-ops/issues/267).

Update signature sorting to also remove any duplicates

---

script/deploy/l1/SetGasLimitBuilder.sol
script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol
test/universal/MultisigBuilder.t.sol
test/universal/NestedMultisigBuilder.t.sol

These were removed as parameters in #97. However, after looking at the changes in ethereum-optimism/superchain-ops#356, it seems simpler if they are just passed in.

Pass state accesses / simPayload to _postCheck

---

script/deploy/l1/SetGasLimitBuilder.sol
script/universal/IGnosisSafe.sol
script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol
script/universal/Signatures.sol
script/universal/Simulation.sol
test/universal/MultisigBuilder.t.sol
test/universal/NestedMultisigBuilder.t.sol

#102 removed the `IGnosisSafe` due to incompatibilities with optimism's interface.
This PR reverts that PR, and removes the `IGnosisSafe` from any function parameters (replacing with `address`) so we can be maximally compatible.

Re-introduce Safe interface, and remove from function signatures

---

script/universal/MultisigBase.sol
script/universal/NestedMultisigBuilder.sol
script/universal/Simulation.sol

#97 introduced a small bug where the outer safe owner was unnecessarily overridden in the simulation. This owner override did not exist prior to this refactor, and is not needed because the simulation doesn't simulate the approval, but rather the inner nested sig tx action (i.e. what the outer signer sig is actually approving).
This PR removes this owner override. Fixes this issue: https://github.com/ethereum-optimism/superchain-ops/pull/363#issuecomment-2455912210

[NestedMultisigBuilder] Don't override signerSafe owner

---

script/universal/MultisigBase.sol
script/universal/MultisigBuilder.sol
script/universal/NestedMultisigBuilder.sol
script/universal/Signatures.sol
script/universal/Simulation.sol
test/universal/NestedMultisigBuilder.t.sol

The `Simulation.sol` library had some `public` methods on it, which causes it to be a separate library contract. This means that anything that interacts with `Simulation` under a `broadcast` context (e.g. within `vm.startBroadcast()`) will deploy the Simulation contract.
This PR switches the library methods from `public` to `internal` which causes the library to be embedded in the script, which prevents it from being deployed.
It also more narrowly scopes down the broadcast context to only apply to the single `safe.execTransaction` to prevent this from happening again in future changes.
Also added a feature that skips signatures from non-owning addresses (and warning via console).

Fix simulation contract deployment during broadcast

---

script/universal/DoubleNestedMultisigBuilder.sol

Allows writing tasks that involve nested and double nested signatures with the same script

extend NestedMultisigBuilder from DoubleNestedMultisigBuilder

---

src/smart-escrow/SmartEscrow.sol

- Corrected misleading documentation for `_start` parameter
- Added missing documentation for `_cliffStart` parameter
- Clarified relationship between `_start` and `_cliffStart` parameters

Fix SmartEscrow constructor parameter documentation

---

script/deploy/l2/tests/DeployTestTokenContracts.s.sol

This pr is to address issue #99 
The `_l1erc721` parameter in `createOptimismMintableERC721` represents the L1 token, while `L1T721` was incorrectly used as the L2 token's symbol. Changed to `L2T721` to properly reflect the relationship between the parameter and the created token.

fix: align token symbol with parameter naming

---

script/universal/DoubleNestedMultisigBuilder.sol

The `DoubleNestedMultisigBuilder` script was incorrectly sharing link generation logic with `NestedMultisigBuilder` resulting in disregarded state diff(s) for the child signer contract. This is needed for Upgrade 15 which is planned to be executed tomorrow. As a result of the time crunch, I just copy/pasted the relevant functions into `DoubleNestedMultisigBuilder` that are seen below. These are taken / modified from `NestedMultisigBase.sol`. Some logic is still shared so this can be refactored in a later PR.
Here's the diff for relevant functions that were modified while adding to `DoubleNestedMultisigBuilder`

fix Tenderly simulation link for double nested multisig builder script

---

script/deploy/l1/SetGasLimit.sol
script/universal/MultisigScript.sol
test/universal/DoubleNestedMultisigBuilder.t.sol
test/universal/MultisigBuilder.t.sol
test/universal/NestedMultisigBuilder.t.sol

Change `_buildCalls` to return an array of `Call3Value`, enabling ETH transfers (primarily for funding new facilitator ledgers).
Update the unit tests with the new expected "data to sign", which changed due to the use of `aggregate3Value` instead of `aggregate3`, and the addition of the `value` field in the `Call3Value` calls.

chore: use Call3Value for _buildCalls

---

src/utils/CBMulticall.sol
test/mocks/MockReceiver.sol
test/utils/CBMulticall.t.sol

Adds the Multicall contract utilized by our eth recovery task. In the regular `Multicall3` contract, the `aggregate3Value` function has the following line:
```solidity
require(msg.value == valAccumulator, "Multicall3: value mismatch");
```
This did not allow us to delegatecall from a multisig because you cannot send a value with this call type. Since our multisig already holds ETH, removing the above `require` statement allows calling `aggregate3Value` via delegatecall.

feat(CHAIN-1796): add CBMulticall contract
